// COMPILER_VERSION: 2.3
// GENERATE_CLASSES_IN_IR: false
// Regression test for duplicate BindsMirror constructors.
//
// When an external FIR extension generates a @ContributesTo interface with a @Binds member, the
// synthetic BindsMirror class is generated by BindingMirrorClassFirGenerator. ContributionsFirGenerator
// used to also claim the mirror's constructor via a blanket name check, causing two identical private
// constructors to be emitted into the FIR. This asserts a single constructor is generated.

package test

import kotlin.reflect.KClass

@Target(AnnotationTarget.CLASS)
annotation class GenerateBindsContribution(val scope: KClass<*>)

interface MyType

@Inject
@GenerateBindsContribution(AppScope::class)
class MyImpl : MyType
