

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/reports")
@TestDataPath("$PROJECT_ROOT")
public class ReportsTestGenerated extends AbstractReportsTest {
  @Test
  public void testAllFilesPresentInReports() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/reports"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("BasicKeysUnusedReport.kt")
  public void testBasicKeysUnusedReport() {
    runTest("compiler-tests/src/test/data/dump/reports/BasicKeysUnusedReport.kt");
  }

  @Test
  @TestMetadata("UnmatchedReplacement.kt")
  public void testUnmatchedReplacement() {
    runTest("compiler-tests/src/test/data/dump/reports/UnmatchedReplacement.kt");
  }
}
