#!/usr/bin/env python3

"""Maps Kotlin Beta and RC releases to the dev compat factory they should use.

Beta and RC releases rank above every dev build of the same base version, so without a mapping
they resolve to the newest dev compat factory. That factory may use APIs the release branch
doesn't have. This script finds the dev build at each prerelease's merge-base with master in
JetBrains/kotlin. It maps the prerelease to the lowest dev compat module at or above that build.
The branch point is recorded in a comment for review.

Only base versions with dev compat modules and no stable module are checked. Prereleases of a
released base resolve against its stable factories without help.

Usage:
  ./fetch-prerelease-kotlin-versions.py

Dependencies: python3, gh (GitHub CLI, authenticated)
"""

import glob
import importlib.util
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "prerelease-mappings.txt")

HEADER = """\
# Copyright (C) 2026 Zac Sweers
# SPDX-License-Identifier: Apache-2.0

# Kotlin prerelease alias mappings
# Generated by fetch-prerelease-kotlin-versions.py
# Format: <prerelease-version>=<dev-version>
#
# Each Beta or RC maps to the lowest dev compat module at or above its branch point from master.
# That's a best guess. Test each prerelease in CI once it's published to confirm it.
"""

PRERELEASE_TAG_RE = re.compile(r"^build-(\d+\.\d+\.\d+)-((?:Beta|RC)\d*)-(?:release-)?(\d+)$")
ENTRY_RE = re.compile(r"^([^#=\s]+)=(\S+)$")
DEV_VERSION_RE = re.compile(r"^(\d+\.\d+\.\d+)-dev-(\d+)$")


def load_ide_script():
    path = os.path.join(SCRIPT_DIR, "fetch-all-ide-kotlin-versions.py")
    spec = importlib.util.spec_from_file_location("fetch_all_ide_kotlin_versions", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def unreleased_dev_modules():
    """Return {base version: sorted dev build numbers} for bases without a stable compat module."""
    dev_builds = {}
    stable_bases = set()
    for version_file in glob.glob(os.path.join(SCRIPT_DIR, "k*", "version.txt")):
        with open(version_file) as f:
            version = f.read().strip()
        dev = DEV_VERSION_RE.match(version)
        if dev:
            dev_builds.setdefault(dev.group(1), []).append(int(dev.group(2)))
        elif re.match(r"^\d+\.\d+\.\d+$", version):
            stable_bases.add(version)
    return {
        base: sorted(builds) for base, builds in dev_builds.items() if base not in stable_bases
    }


def pick_dev_module(base, module_builds, branch_point):
    """Pick the lowest dev module at or above the branch point, or the newest one."""
    branch_build = int(DEV_VERSION_RE.match(branch_point).group(2))
    for build in module_builds:
        if build >= branch_build:
            return f"{base}-dev-{build}"
    return f"{base}-dev-{module_builds[-1]}"


def read_existing_entries():
    """Read existing mappings and their comments so entries that fail to resolve are kept."""
    entries = {}
    if not os.path.exists(OUTPUT_FILE):
        return entries
    comment = None
    with open(OUTPUT_FILE) as f:
        for line in f:
            line = line.strip()
            m = ENTRY_RE.match(line)
            if m:
                entries[m.group(1)] = (m.group(2), comment)
                comment = None
            elif line.startswith("# build-"):
                comment = line
            else:
                comment = None
    return entries


def latest_prerelease_tags(ide, base):
    """Return {prerelease version: newest build tag} for a base version."""
    latest = {}
    for prefix in (f"build-{base}-Beta", f"build-{base}-RC"):
        for tag in ide.fetch_kotlin_tags(prefix):
            m = PRERELEASE_TAG_RE.match(tag)
            if not m:
                continue
            version = f"{m.group(1)}-{m.group(2)}"
            build = int(m.group(3))
            if version not in latest or build > latest[version][0]:
                latest[version] = (build, tag)
    return {version: tag for version, (_, tag) in latest.items()}


def version_sort_key(version):
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)-(Beta|RC)(\d*)$", version)
    if not m:
        return ((0, 0, 0), 0, 0)
    maturity = 0 if m.group(4) == "Beta" else 1
    number = int(m.group(5)) if m.group(5) else 0
    return ((int(m.group(1)), int(m.group(2)), int(m.group(3))), maturity, number)


def main():
    ide = load_ide_script()
    entries = read_existing_entries()
    modules = unreleased_dev_modules()
    print(f"Checking prereleases for: {', '.join(sorted(modules)) or '(none)'}")

    for base, module_builds in sorted(modules.items()):
        for version, tag in sorted(latest_prerelease_tags(ide, base).items()):
            merge_base = ide.get_merge_base(tag)
            if not merge_base:
                print(f"  {version}: could not find a merge base for {tag}", file=sys.stderr)
                continue
            branch_point = ide.find_dev_build_at_merge_base(base, merge_base)
            if not branch_point:
                print(f"  {version}: no dev build found at {merge_base[:10]}", file=sys.stderr)
                continue
            target = pick_dev_module(base, module_builds, branch_point)
            print(f"  {version}: {tag} branched at {branch_point} -> {target}")
            entries[version] = (target, f"# {tag} branched at {branch_point}")

    with open(OUTPUT_FILE, "w") as f:
        f.write(HEADER)
        if entries:
            f.write("\n")
        for version in sorted(entries, key=version_sort_key):
            target, comment = entries[version]
            if comment:
                f.write(f"{comment}\n")
            f.write(f"{version}={target}\n")
    print(f"Wrote {len(entries)} entries to {os.path.basename(OUTPUT_FILE)}")


if __name__ == "__main__":
    main()
