// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.trace.internal

import dev.zacsweers.metro.MembersInjector

/**
 * [MembersInjector] decorator used by Metro-generated code when runtime tracing is enabled.
 *
 * Each invocation emits an instant event for the injection operation, then delegates to [injector].
 *
 * @param traceContext graph-local tracing state generated by Metro.
 * @param qualifier rendered binding qualifier, or `null` when the injector is unqualified.
 * @param type rendered canonical target type without its qualifier.
 * @param injector Metro [MembersInjector] that performs the injection.
 */
public class TracedMembersInjector<T : Any>(
  private val traceContext: MetroTraceContext,
  private val qualifier: String?,
  private val type: String,
  private val injector: MembersInjector<T>,
) : MembersInjector<T> {
  override fun injectMembers(instance: T) {
    traceContext.instant(
      name = "MembersInjector<$type>",
      callable = "injectMembers",
      qualifier = qualifier,
      type = type,
      contextualType = null,
      kind = "Member Injector",
    )
    injector.injectMembers(instance)
  }
}
