// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
@file:OptIn(ExperimentalMetroCoroutinesApi::class)

package dev.zacsweers.metro.trace.internal

import dev.zacsweers.metro.ExperimentalMetroCoroutinesApi
import dev.zacsweers.metro.SuspendProvider

/**
 * SuspendProvider decorator used by Metro-generated code when runtime tracing is enabled.
 *
 * Each invocation opens a coroutine-aware trace section for [type], delegates to [provider], and
 * closes the section even if the delegate throws or is cancelled. The section stays attached to the
 * invoking coroutine across suspension points.
 *
 * @param traceContext graph-local tracing state generated by Metro.
 * @param qualifier rendered binding qualifier, or `null` when the binding is unqualified.
 * @param type rendered canonical type without its qualifier.
 * @param kind rendered binding implementation kind, or `null` when codegen has not supplied one.
 * @param provider Metro suspend provider that creates or returns the binding value.
 */
public class TracedSuspendProvider<T>(
  private val traceContext: MetroTraceContext,
  private val qualifier: String?,
  private val type: String,
  private val kind: String?,
  private val provider: SuspendProvider<T>,
) : SuspendProvider<T> {
  override suspend fun invoke(): T {
    return traceContext.traceSuspend(
      qualifier = qualifier,
      type = type,
      contextualType = null,
      kind = kind,
    ) {
      provider.invoke()
    }
  }
}
